# Example config file for running LE LCCS rules on Open Data Cube
extent:
    min_x: 1500000.000
    max_x: 1600000.000
    min_y: -2200000.000
    max_y: -2100000.000

resolution: [100, -100]
crs: "EPSG:3577"

output_tiff: "level3_out.tif"
output_rgb_tiff: "level3_out_rgb.tif"

Layers:
    vegetat_veg_cat:
        ingest_class: gridded_ingest.LEIngestODC
        product: fc_percentile_albers_annual
        measurements: [BS_PC_50]
        start_time: 2017-01-01
        end_time: 2017-12-31
        expstr: "(BS_PC_50 < 0.4)"

    aquatic_wat_cat:
        ingest_class: gridded_ingest.LEIngestODC
        product: wofs_annual_summary
        measurements: [frequency]
        start_time: 2017-01-01
        end_time: 2018-01-15
        expstr: "frequency >= 20"

    artwatr_wat_cat:
        ingest_class: gridded_ingest.LEIngestODC
        product: geofabric
        measurements: [band1]
        start_time: 2014-02-01
        end_time: 2014-03-01
        expstr: "(band1 == 1) | (band1 == 8)"

#    cultman_agr_cat:
#        ingest_class: gridded_ingest.LEIngestGDAL
#        input_file: /g/data/r78/LCCS_Aberystwyth/static_layers/clum_50m0917m.tif
#        resampling: mode
#        expstr: "((band > 210) & (band <= 353)) | ((band > 400) & (band <= 454)) | ((band > 510) & (band <= 528))"
#
#    artific_urb_cat:
#        ingest_class: gridded_ingest.LEIngestGDAL
#        input_file: /g/data/r78/LCCS_Aberystwyth/static_layers/clum_50m0917m.tif
#        resampling: mode
#        expstr: "(band == 500) | ((band > 530) & (band <= 575))"

